= Pomo

A quick n' dirty Pomodoro timer for the command line, for use with the Windows Subsystem for Linux.

*Warning*: Probably not usable by anyone but me, completely untested. 

== Rationale
I couldn't find a simple, command line-based Pomodoro timer that was usable with WSL, could display 
a notification instead of playing a sound, and didn't drain my battery like crazy, so I wrote my 
own.

== Installation
Pomo requires http://vaskovsky.net/notify-send/[notify-send] to be on the system path.

To install (currently must be built from source):
----
git clone https://github.com/syvsto/pomo.git && cd pomo/
cargo build --release
----

== Running
Copy the resulting executable (found in `./target/release/`) to somewhere on the system path,
followed by `pomo` for default Pomodoro timings.

*OR*

`cargo run --release` inside the project directory.

== Arguments

*--work, -w*: Set the time in minutes of the work sessions (defaults to 25)

*--shortbreak, -s*: Set the time in minutes of the short breaks (defaults to 5)

*--longbreak, -l*: Set the time in minutes of the long breaks (defaults to 20)
